<?php



/**
 * This class defines the structure of the 'solution' table.
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Jan  7 23:45:26 2013
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    propel.generator.lib.model.map
 */
class SolutionTableMap extends TableMap
{

    /**
     * The (dot-path) name of this class
     */
    const CLASS_NAME = 'lib.model.map.SolutionTableMap';

    /**
     * Initialize the table attributes, columns and validators
     * Relations are not initialized by this method since they are lazy loaded
     *
     * @return void
     * @throws PropelException
     */
    public function initialize()
    {
        // attributes
        $this->setName('solution');
        $this->setPhpName('Solution');
        $this->setClassname('Solution');
        $this->setPackage('lib.model');
        $this->setUseIdGenerator(true);
        // columns
        $this->addPrimaryKey('ID', 'Id', 'INTEGER', true, 11, null);
        $this->addColumn('PROBLEM_ID', 'ProblemId', 'INTEGER', true, 11, null);
        $this->addColumn('STEP', 'Step', 'INTEGER', true, 4, null);
        $this->addColumn('INSTRUCTION', 'Instruction', 'LONGVARCHAR', true, null, null);
        $this->addColumn('INSTRUCTION_TYPE_ID', 'InstructionTypeId', 'INTEGER', true, 4, 10);
        // validators
    } // initialize()

    /**
     * Build the RelationMap objects for this table relationships
     */
    public function buildRelations()
    {
    } // buildRelations()

    /**
     *
     * Gets the list of behaviors registered for this table
     *
     * @return array Associative array (name => parameters) of behaviors
     */
    public function getBehaviors()
    {
        return array(
            'symfony' => array('form' => 'true', 'filter' => 'true', ),
            'symfony_behaviors' => array(),
        );
    } // getBehaviors()

} // SolutionTableMap
