<?php


/**
 * Base class that represents a query for the 'solution' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Mon Jan  7 23:45:26 2013
 *
 * @method SolutionQuery orderById($order = Criteria::ASC) Order by the id column
 * @method SolutionQuery orderByProblemId($order = Criteria::ASC) Order by the problem_id column
 * @method SolutionQuery orderByStep($order = Criteria::ASC) Order by the step column
 * @method SolutionQuery orderByInstruction($order = Criteria::ASC) Order by the instruction column
 * @method SolutionQuery orderByInstructionTypeId($order = Criteria::ASC) Order by the instruction_type_id column
 *
 * @method SolutionQuery groupById() Group by the id column
 * @method SolutionQuery groupByProblemId() Group by the problem_id column
 * @method SolutionQuery groupByStep() Group by the step column
 * @method SolutionQuery groupByInstruction() Group by the instruction column
 * @method SolutionQuery groupByInstructionTypeId() Group by the instruction_type_id column
 *
 * @method SolutionQuery leftJoin($relation) Adds a LEFT JOIN clause to the query
 * @method SolutionQuery rightJoin($relation) Adds a RIGHT JOIN clause to the query
 * @method SolutionQuery innerJoin($relation) Adds a INNER JOIN clause to the query
 *
 * @method Solution findOne(PropelPDO $con = null) Return the first Solution matching the query
 * @method Solution findOneOrCreate(PropelPDO $con = null) Return the first Solution matching the query, or a new Solution object populated from the query conditions when no match is found
 *
 * @method Solution findOneById(int $id) Return the first Solution filtered by the id column
 * @method Solution findOneByProblemId(int $problem_id) Return the first Solution filtered by the problem_id column
 * @method Solution findOneByStep(int $step) Return the first Solution filtered by the step column
 * @method Solution findOneByInstruction(string $instruction) Return the first Solution filtered by the instruction column
 * @method Solution findOneByInstructionTypeId(int $instruction_type_id) Return the first Solution filtered by the instruction_type_id column
 *
 * @method array findById(int $id) Return Solution objects filtered by the id column
 * @method array findByProblemId(int $problem_id) Return Solution objects filtered by the problem_id column
 * @method array findByStep(int $step) Return Solution objects filtered by the step column
 * @method array findByInstruction(string $instruction) Return Solution objects filtered by the instruction column
 * @method array findByInstructionTypeId(int $instruction_type_id) Return Solution objects filtered by the instruction_type_id column
 *
 * @package    propel.generator.lib.model.om
 */
abstract class BaseSolutionQuery extends ModelCriteria
{
    /**
     * Initializes internal state of BaseSolutionQuery object.
     *
     * @param     string $dbName The dabase name
     * @param     string $modelName The phpName of a model, e.g. 'Book'
     * @param     string $modelAlias The alias for the model in this query, e.g. 'b'
     */
    public function __construct($dbName = 'propel', $modelName = 'Solution', $modelAlias = null)
    {
        parent::__construct($dbName, $modelName, $modelAlias);
    }

    /**
     * Returns a new SolutionQuery object.
     *
     * @param     string $modelAlias The alias of a model in the query
     * @param     SolutionQuery|Criteria $criteria Optional Criteria to build the query from
     *
     * @return SolutionQuery
     */
    public static function create($modelAlias = null, $criteria = null)
    {
        if ($criteria instanceof SolutionQuery) {
            return $criteria;
        }
        $query = new SolutionQuery();
        if (null !== $modelAlias) {
            $query->setModelAlias($modelAlias);
        }
        if ($criteria instanceof Criteria) {
            $query->mergeWith($criteria);
        }

        return $query;
    }

    /**
     * Find object by primary key.
     * Propel uses the instance pool to skip the database if the object exists.
     * Go fast if the query is untouched.
     *
     * <code>
     * $obj  = $c->findPk(12, $con);
     * </code>
     *
     * @param mixed $key Primary key to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return   Solution|Solution[]|mixed the result, formatted by the current formatter
     */
    public function findPk($key, $con = null)
    {
        if ($key === null) {
            return null;
        }
        if ((null !== ($obj = SolutionPeer::getInstanceFromPool((string) $key))) && !$this->formatter) {
            // the object is alredy in the instance pool
            return $obj;
        }
        if ($con === null) {
            $con = Propel::getConnection(SolutionPeer::DATABASE_NAME, Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        if ($this->formatter || $this->modelAlias || $this->with || $this->select
         || $this->selectColumns || $this->asColumns || $this->selectModifiers
         || $this->map || $this->having || $this->joins) {
            return $this->findPkComplex($key, $con);
        } else {
            return $this->findPkSimple($key, $con);
        }
    }

    /**
     * Find object by primary key using raw SQL to go fast.
     * Bypass doSelect() and the object formatter by using generated code.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return   Solution A model object, or null if the key is not found
     * @throws   PropelException
     */
    protected function findPkSimple($key, $con)
    {
        $sql = 'SELECT `ID`, `PROBLEM_ID`, `STEP`, `INSTRUCTION`, `INSTRUCTION_TYPE_ID` FROM `solution` WHERE `ID` = :p0';
        try {
            $stmt = $con->prepare($sql);
            $stmt->bindValue(':p0', $key, PDO::PARAM_INT);
            $stmt->execute();
        } catch (Exception $e) {
            Propel::log($e->getMessage(), Propel::LOG_ERR);
            throw new PropelException(sprintf('Unable to execute SELECT statement [%s]', $sql), $e);
        }
        $obj = null;
        if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
            $obj = new Solution();
            $obj->hydrate($row);
            SolutionPeer::addInstanceToPool($obj, (string) $key);
        }
        $stmt->closeCursor();

        return $obj;
    }

    /**
     * Find object by primary key.
     *
     * @param     mixed $key Primary key to use for the query
     * @param     PropelPDO $con A connection object
     *
     * @return Solution|Solution[]|mixed the result, formatted by the current formatter
     */
    protected function findPkComplex($key, $con)
    {
        // As the query uses a PK condition, no limit(1) is necessary.
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKey($key)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->formatOne($stmt);
    }

    /**
     * Find objects by primary key
     * <code>
     * $objs = $c->findPks(array(12, 56, 832), $con);
     * </code>
     * @param     array $keys Primary keys to use for the query
     * @param     PropelPDO $con an optional connection object
     *
     * @return PropelObjectCollection|Solution[]|mixed the list of results, formatted by the current formatter
     */
    public function findPks($keys, $con = null)
    {
        if ($con === null) {
            $con = Propel::getConnection($this->getDbName(), Propel::CONNECTION_READ);
        }
        $this->basePreSelect($con);
        $criteria = $this->isKeepQuery() ? clone $this : $this;
        $stmt = $criteria
            ->filterByPrimaryKeys($keys)
            ->doSelect($con);

        return $criteria->getFormatter()->init($criteria)->format($stmt);
    }

    /**
     * Filter the query by primary key
     *
     * @param     mixed $key Primary key to use for the query
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKey($key)
    {

        return $this->addUsingAlias(SolutionPeer::ID, $key, Criteria::EQUAL);
    }

    /**
     * Filter the query by a list of primary keys
     *
     * @param     array $keys The list of primary key to use for the query
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByPrimaryKeys($keys)
    {

        return $this->addUsingAlias(SolutionPeer::ID, $keys, Criteria::IN);
    }

    /**
     * Filter the query on the id column
     *
     * Example usage:
     * <code>
     * $query->filterById(1234); // WHERE id = 1234
     * $query->filterById(array(12, 34)); // WHERE id IN (12, 34)
     * $query->filterById(array('min' => 12)); // WHERE id > 12
     * </code>
     *
     * @param     mixed $id The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterById($id = null, $comparison = null)
    {
        if (is_array($id) && null === $comparison) {
            $comparison = Criteria::IN;
        }

        return $this->addUsingAlias(SolutionPeer::ID, $id, $comparison);
    }

    /**
     * Filter the query on the problem_id column
     *
     * Example usage:
     * <code>
     * $query->filterByProblemId(1234); // WHERE problem_id = 1234
     * $query->filterByProblemId(array(12, 34)); // WHERE problem_id IN (12, 34)
     * $query->filterByProblemId(array('min' => 12)); // WHERE problem_id > 12
     * </code>
     *
     * @param     mixed $problemId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByProblemId($problemId = null, $comparison = null)
    {
        if (is_array($problemId)) {
            $useMinMax = false;
            if (isset($problemId['min'])) {
                $this->addUsingAlias(SolutionPeer::PROBLEM_ID, $problemId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($problemId['max'])) {
                $this->addUsingAlias(SolutionPeer::PROBLEM_ID, $problemId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(SolutionPeer::PROBLEM_ID, $problemId, $comparison);
    }

    /**
     * Filter the query on the step column
     *
     * Example usage:
     * <code>
     * $query->filterByStep(1234); // WHERE step = 1234
     * $query->filterByStep(array(12, 34)); // WHERE step IN (12, 34)
     * $query->filterByStep(array('min' => 12)); // WHERE step > 12
     * </code>
     *
     * @param     mixed $step The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByStep($step = null, $comparison = null)
    {
        if (is_array($step)) {
            $useMinMax = false;
            if (isset($step['min'])) {
                $this->addUsingAlias(SolutionPeer::STEP, $step['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($step['max'])) {
                $this->addUsingAlias(SolutionPeer::STEP, $step['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(SolutionPeer::STEP, $step, $comparison);
    }

    /**
     * Filter the query on the instruction column
     *
     * Example usage:
     * <code>
     * $query->filterByInstruction('fooValue');   // WHERE instruction = 'fooValue'
     * $query->filterByInstruction('%fooValue%'); // WHERE instruction LIKE '%fooValue%'
     * </code>
     *
     * @param     string $instruction The value to use as filter.
     *              Accepts wildcards (* and % trigger a LIKE)
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByInstruction($instruction = null, $comparison = null)
    {
        if (null === $comparison) {
            if (is_array($instruction)) {
                $comparison = Criteria::IN;
            } elseif (preg_match('/[\%\*]/', $instruction)) {
                $instruction = str_replace('*', '%', $instruction);
                $comparison = Criteria::LIKE;
            }
        }

        return $this->addUsingAlias(SolutionPeer::INSTRUCTION, $instruction, $comparison);
    }

    /**
     * Filter the query on the instruction_type_id column
     *
     * Example usage:
     * <code>
     * $query->filterByInstructionTypeId(1234); // WHERE instruction_type_id = 1234
     * $query->filterByInstructionTypeId(array(12, 34)); // WHERE instruction_type_id IN (12, 34)
     * $query->filterByInstructionTypeId(array('min' => 12)); // WHERE instruction_type_id > 12
     * </code>
     *
     * @param     mixed $instructionTypeId The value to use as filter.
     *              Use scalar values for equality.
     *              Use array values for in_array() equivalent.
     *              Use associative array('min' => $minValue, 'max' => $maxValue) for intervals.
     * @param     string $comparison Operator to use for the column comparison, defaults to Criteria::EQUAL
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function filterByInstructionTypeId($instructionTypeId = null, $comparison = null)
    {
        if (is_array($instructionTypeId)) {
            $useMinMax = false;
            if (isset($instructionTypeId['min'])) {
                $this->addUsingAlias(SolutionPeer::INSTRUCTION_TYPE_ID, $instructionTypeId['min'], Criteria::GREATER_EQUAL);
                $useMinMax = true;
            }
            if (isset($instructionTypeId['max'])) {
                $this->addUsingAlias(SolutionPeer::INSTRUCTION_TYPE_ID, $instructionTypeId['max'], Criteria::LESS_EQUAL);
                $useMinMax = true;
            }
            if ($useMinMax) {
                return $this;
            }
            if (null === $comparison) {
                $comparison = Criteria::IN;
            }
        }

        return $this->addUsingAlias(SolutionPeer::INSTRUCTION_TYPE_ID, $instructionTypeId, $comparison);
    }

    /**
     * Exclude object from result
     *
     * @param   Solution $solution Object to remove from the list of results
     *
     * @return SolutionQuery The current query, for fluid interface
     */
    public function prune($solution = null)
    {
        if ($solution) {
            $this->addUsingAlias(SolutionPeer::ID, $solution->getId(), Criteria::NOT_EQUAL);
        }

        return $this;
    }

}
