<?php



/**
 * Skeleton subclass for performing query and update operations on the 'problem' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Dec 30 00:33:48 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class ProblemPeer extends BaseProblemPeer
{

  public static function getActiveProblems() {

    $problems = ProblemQuery::create()
              ->filterByIsActive(1)
              ->find();

    return $problems;

  }

  public static function deleteProblem($id) {

    ProblemQuery::create()
                ->filterById($id)
                ->delete();

    return 0;
    
  }
}
