<?php



/**
 * Skeleton subclass for performing query and update operations on the 'solution' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.6.7 on:
 *
 * Sun Dec 30 00:33:48 2012
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.lib.model
 */
class SolutionPeer extends BaseSolutionPeer
{
  public static function getSolutionToProblem($problemId) {

    $solutions = SolutionQuery::create()
               ->filterByProblemId($problemId)
               ->orderByStep()
               ->find();

    return $solutions;
  }
  
  public static function getAllSolutions() {

    $solutions = SolutionQuery::create()
               ->orderByProblemId()
               ->orderByStep()
               ->find();

    return $solutions;
  }
}
