dev:
  propel:
    param:
      classname: DebugPDO
      debug: { realmemoryusage: true, details: { time: { enabled: true }, slow: { enabled: true, threshold: 0.1 }, mem: { enabled: true }, mempeak: { enabled: true }, memdelta: { enabled: true } } }

test:
  propel:
    param:
      classname: DebugPDO

prod:
  propel:
    class: sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:host=localhost;dbname=sublime_prod
      username:   sublime_prod
      password:   sublime_prod
      encoding:   utf8
      persistent: true
      pooling:    true

dev:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=sublime;host=localhost
      username:   sublime
      password:   sublime
      encoding:   utf8
      persistent: true
      pooling:    true
